src/AIE/Bundle/AnomalyBundle/Entity/Registrar.php
<?php
/**
 * Created by Khalid Alnajjar (mokha)
 * Date: 04/01/16
 * Time: 20:23
 */

namespace AIE\Bundle\AnomalyBundle\Entity;


use AIE\Bundle\VeracityBundle\Component\Core\Tags;
use Doctrine\ORM\Mapping as ORM;
use AIE\Bundle\UserBundle\Entity\User as User;
use JMS\Serializer\Annotation as JMS;

/**
 * Registrar
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AIE\Bundle\AnomalyBundle\Entity\RegistrarRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="registrar_type", type="string")
 * @ORM\DiscriminatorMap({
 * "AN" = "AnomalyRegistrar", "MR"="MarineAnomaly",
 * "PL" = "PipelineAnomaly", "PI" = "PipingAnomaly", "ST"="StructureAnomaly", "SE"="StaticEquipmentAnomaly",
 * "RO" = "RepairOrderRegistrar", "TRO" = "TemporaryRepairOrderRegistrar", "FM" = "FabricMaintenanceRegistrar",
 * "AS" = "AssessmentRegistrar", "AC" = "ActionRegistrar",
 * })
 * @JMS\Discriminator(disabled=true)
 * @JMS\ExclusionPolicy("None")
 */
class Registrar
{
    use Tags;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\Type("integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Projects", inversedBy="registrars")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     * @JMS\Exclude
     */
    protected $project;

    /**
     * The index of the status from statusChoices
     *
     * @var integer
     *
     * @ORM\Column(name="status", type="integer")
     * @JMS\Type("integer")
     */
    protected $status;

    /**
     * @ORM\ManyToOne(targetEntity="ActionOwners", inversedBy="registrars")
     * @ORM\JoinColumn(name="spa_id", referencedColumnName="id")
     * @JMS\Exclude
     */
    protected $spa;

    /**
     * @ORM\ManyToOne(targetEntity="ApprovalOwners", inversedBy="registrars")
     * @ORM\JoinColumn(name="approved_spa_id", referencedColumnName="id")
     * @JMS\Exclude
     */
    protected $approvedspa;

    /**
     * @var User
     *
     * @JMS\Exclude
     * @JMS\ReadOnly
     */
    protected $spaUser;

    /**
     * A number that Starts from 0 and increments by 1 every time the Action is deferred
     *
     * @var double
     *
     * @ORM\Column(name="deferred", type="integer")
     * @JMS\Type("integer")
     */
    protected $deferred = 0;

    /**
     * @var string
     *
     * @ORM\Column(name="deferral_justification", type="text", nullable=true)
     * @JMS\Type("string")
     */
    protected $deferralJustification;

    /**
     * @var string
     *
     * @ORM\Column(name="deferral_safe_justification", type="text", nullable=true)
     * @JMS\Type("string")
     */
    protected $deferralSafeJustification;


    /**
     * @ORM\ManyToMany(targetEntity="Files")
     * @ORM\JoinTable(name="RegistrarFiles",
     *      joinColumns={@ORM\JoinColumn(name="action_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="file_id", referencedColumnName="id")}
     * )
     * @JMS\Exclude
     */
    protected $registrarFiles;

    /**
     * @ORM\OneToMany(targetEntity="Request" , mappedBy="registrar", cascade={"all"}, fetch="EXTRA_LAZY")
     * @JMS\Exclude
     */
    protected $requests;


    /**
     * @var string
     *
     * @ORM\Column(name="deferral_reject_justification", type="text", nullable=true)
     * @JMS\Type("string")
     */
    protected $deferralRejectJustification;

    /**
     * @var array
     *
     * @JMS\Type("array")
     * @JMS\Exclude
     * @JMS\ReadOnly
     */
    static protected $criticalityChoices = [
        0 => 'Low',
        1 => 'Medium',
        2 => 'High'
    ];

    /**
     * @var array
     *
     * @JMS\Type("array")
     * @JMS\Exclude
     * @JMS\ReadOnly
     */
    protected $statusChoices = ['Live', 'Closed', 'Cancelled'];

    /**
     * @var array
     *
     * @JMS\Type("array")
     * @JMS\Exclude
     * @JMS\ReadOnly
     */
    protected $stageChoices = ['new'=>'New', 'request'=>'Pending', 'request-rejected'=>'Rejected'];

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @JMS\VirtualProperty
     * @JMS\SerializedName("project_id")
     */
    public function getProjectId()
    {
        return ($this->project) ? $this->project->getId() : null;
    }

    /**
     * @JMS\VirtualProperty
     * @JMS\SerializedName("spa_id")
     */
    public function getSpaId()
    {
        return ($this->spa) ? $this->spa->getId() : null;
    }

    /**
     * Get deferred
     *
     * @return integer
     */
    public function getDeferred()
    {
        return $this->deferred;
    }

    /**
     * Set deferralJustification
     *
     * @param string $deferralJustification
     * @return Registrar
     */
    public function setDeferralJustification($deferralJustification)
    {
        $this->deferralJustification = $deferralJustification;

        return $this;
    }

    /**
     * Get deferralJustification
     *
     * @return string
     */
    public function getDeferralJustification()
    {
        return $this->deferralJustification;
    }

    /**
     * Set deferred
     *
     * @param integer $deferred
     * @return Registrar
     */
    public function setDeferred($deferred)
    {
        $this->deferred = $deferred;

        return $this;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Registrar
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return User
     */
    public function getSpaUser()
    {
        return $this->spaUser;
    }

    public function setSpaUser(User $spaUser)
    {
        $this->spaUser = $spaUser;
    }

    public static function getCriticalityChoices()
    {
        return self::$criticalityChoices;
    }

    public static function getRiskChoices($numerical=true) {
        return RiskMatrix::getRiskChoices($numerical);
    }

    public function getStatusChoices()
    {
        return $this->statusChoices;
    }

    public function getStageChoices()
    {
        return $this->stageChoices;
    }

    /**
     * Set project
     *
     * @param \AIE\Bundle\AnomalyBundle\Entity\Projects $project
     * @return Registrar
     */
    public function setProject(\AIE\Bundle\AnomalyBundle\Entity\Projects $project = null)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return \AIE\Bundle\AnomalyBundle\Entity\Projects
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @JMS\VirtualProperty
     * @JMS\SerializedName("files")
     */
    public function getVirtualFiles()
    {
        $files = [];
        foreach ($this->getRegistrarFiles() as $file) {
            $files[] = $file;
        }

        return $files;
    }

    public function getIsDue()
    {
        //if today is the next inspection or after that
        $now = new \DateTime('now');
        return ($this->getDueDate() !== null && (int)$this->getDueDate()->format('U') <= (int)$now->format('U'));
    }


    // public function getAnomalyIsDue()
    // {
    //     //if today is the next inspection or after that
    //     $now = new \DateTime('now');
    //     return ($this->getNextInspectionDate() !== null && (int)$this->getNextInspectionDate()->format('U') <= (int)$now->format('U'));
    // }


    public function getCode()
    {
        throw new \Exception("Define Anomaly Code");
    }

    public static function getTagChoices()
    {
        return [
            'new' => [
                'name' => 'new',
                'label' => 'new'
            ], //when posted fresh, still admin didn't approve
            'cancelled' => [
                'name' => 'cancelled',
                'label' => 'cancelled'
            ],
            'closed' => [
                'name' => 'closed',
                'label' => 'closed'
            ],
            'final' => [
                'name' => 'final',
                'label' => 'approved',
            ], //admin approved (whether it is create or update)
            'request' => [
                'name' => 'request',
                'label' => 'pending'
            ], //a request was sent
            'request-rejected' => [
                'name' => 'request-rejected',
                'label' => 'rejected'
            ], //request was rejected
        ]; //a mapping between tags and colors
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->files = new \Doctrine\Common\Collections\ArrayCollection();
        $this->registrarFiles = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add registrarFiles
     *
     * @param \AIE\Bundle\AnomalyBundle\Entity\Files $registrarFiles
     * @return Registrar
     */
    public function addRegistrarFile(\AIE\Bundle\AnomalyBundle\Entity\Files $registrarFiles)
    {
        $this->registrarFiles[] = $registrarFiles;

        return $this;
    }

    /**
     * Remove registrarFiles
     *
     * @param \AIE\Bundle\AnomalyBundle\Entity\Files $registrarFiles
     */
    public function removeRegistrarFile(\AIE\Bundle\AnomalyBundle\Entity\Files $registrarFiles)
    {
        $this->registrarFiles->removeElement($registrarFiles);
    }


src/AIE/Bundle/AnomalyBundle/Entity/RepairOrderRegistrar.php
<?php

namespace AIE\Bundle\AnomalyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;

/**
 * RepairOrderRegistrar
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AIE\Bundle\AnomalyBundle\Repository\RepairOrderRegistrarRepository")
 * @JMS\ExclusionPolicy("None")
 */
class RepairOrderRegistrar extends ActionRegistrar
{

	/**
	 * @var string
	 *
	 * @ORM\Column(name="description", type="text", nullable=true)
	 */
	protected $description;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="location_details", type="text", nullable=true)
	 */
	protected $locationDetails;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="repair_priority", type="text", nullable=true)
	 */
	protected $repairPriority;

	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="close_out_date", type="datetime", nullable=true)
	 * @JMS\Type("DateTime")
	 */
	protected $closeOutDate;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="closeOutJustification", type="text", nullable=true)
	 */
	protected $closeOutJustification;


	public function getCode(){
		return 'RO';
	}

    /**
     * Set description
     *
     * @param string $description
     * @return RepairOrderRegistrar
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set locationDetails
     *
     * @param string $locationDetails
     * @return RepairOrderRegistrar
     */
    public function setLocationDetails($locationDetails)
    {
        $this->locationDetails = $locationDetails;

        return $this;
    }

    /**
     * Get locationDetails
     *
     * @return string 
     */
    public function getLocationDetails()
    {
        return $this->locationDetails;
    }

    /**
     * Set repairPriority
     *
     * @param string $repairPriority
     * @return RepairOrderRegistrar
     */
    public function setRepairPriority($repairPriority)
    {
        $this->repairPriority = $repairPriority;

        return $this;
    }

    /**
     * Get repairPriority
     *
     * @return string 
     */
    public function getRepairPriority()
    {
        return $this->repairPriority;
    }

    /**
     * Set closeOutDate
     *
     * @param \DateTime $closeOutDate
     * @return RepairOrderRegistrar
     */
    public function setCloseOutDate($closeOutDate)
    {
        $this->closeOutDate = $closeOutDate;

        return $this;
    }

    /**
     * Get closeOutDate
     *
     * @return \DateTime 
     */
    public function getCloseOutDate()
    {
        return $this->closeOutDate;
    }

    /**
     * Set closeOutJustification
     *
     * @param string $closeOutJustification
     * @return RepairOrderRegistrar
     */
    public function setCloseOutJustification($closeOutJustification)
    {
        $this->closeOutJustification = $closeOutJustification;

        return $this;
    }

    /**
     * Get closeOutJustification
     *
     * @return string 
     */
    public function getCloseOutJustification()
    {
        return $this->closeOutJustification;
    }
}

src/AIE/Bundle/AnomalyBundle/Controller/RepairOrderRegistrarController.php
<?php

namespace AIE\Bundle\AnomalyBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * RepairOrderRegistrar controller.
 *
 * @Route("projects/{projectId}/ro/{type}/", defaults={"type"=null}, requirements={"type"="(pl|pi|se|st|mr)?"})
 */
class RepairOrderRegistrarController extends ActionRegistrarController {


	protected $registrarClassName = 'RepairOrderRegistrar';
	protected $registrarClass = 'AIE\Bundle\AnomalyBundle\Entity\RepairOrderRegistrar';
	protected $registrarRouteBase = 'anomaly_ro';
	protected $registrarType = 'AIE\Bundle\AnomalyBundle\Form\RepairOrderRegistrarType';

    /**
     * Show the request history of an anomaly
     *
     * @Route("{id}/history", name="ro_registrar_request_history")
     * @Method("GET")
     * @Template("AIEAnomalyBundle:Registrar:history.html.twig")
     */
    public function historyAction($id)
    {
        return parent::historyAction($id);
    }

	/**
	 * Lists all entities.
	 *
	 * @Route("", name="anomaly_ro")
	 * @Method({"GET", "POST"})
	 * @Template()
	 */
	public function indexAction(Request $request, $projectId, $type = null) {
		return parent::indexAction($request, $projectId, $type);
	}

	/**
	 * Lists all entities.
	 *
	 * @Route("master", name="anomaly_ro_master")
	 * @Method({"GET", "POST"})
	 * @Template()
	 */
	public function masterAction(Request $request, $projectId, $type = null) {
		$this->registrarRouteBase = 'anomaly_ro_master';
		return parent::masterAction($request, $projectId, $type);
	}

	/**
	 * Finds and displays a entity.
	 *
	 * @Route("show/{id}", name="anomaly_ro_show", requirements={"id": "\d+"})
	 * @Method("GET")
	 * @Template()
	 */
	public function showAction($id, $projectId) {
		return parent::showAction($id, $projectId);
	}

	/**
	 * Finds and displays a entity.
	 *
	 * @Route("showdeferral/{id}", name="anomaly_ro_show_deferral", requirements={"id": "\d+"})
	 * @Method("GET")
	 * @Template()
	 */
	public function showdeferralAction($id, $projectId) {
		return parent::showDeferralAction($id, $projectId);
	}

	/**
	 * Displays a form to edit an existing entity.
	 *
	 * @Route("edit/{id}", name="anomaly_ro_edit")
	 * @Method("GET")
	 * @Template()
	 */
	public function editAction($id, $projectId, $type=null) {
		return parent::editAction($id, $projectId, $type);
	}


	/**
	 * Edits an existing entity.
	 *
	 * @Route("update/{id}", name="anomaly_ro_update")
	 * @Method("PUT")
	 * @Template("AIEAnomalyBundle:RepairOrderRegistrar:edit.html.twig")
	 */
	public function updateAction(Request $request, $projectId, $id, $type) {
		return parent::updateAction($request, $projectId, $id, $type);
	}

	protected function setEntityFields($entity, $data) {
		parent::setEntityFields($entity, $data);
	}
}

src/AIE/Bundle/AnomalyBundle/Resources/views/RepairOrderRegistrar/edit.html.twig
{% extends 'AIEAnomalyBundle:ActionRegistrar:edit.html.twig' %}
{% set action_type = 'Repair Order' %}

{% block content -%}
    <h1>{{ action_type }}</h1>

    {{ form_start(edit_form) }}
    {{ parent() }}
    {{ form_widget(edit_form) }}
    {{ form_end(edit_form) }}

    <ul class="nav nav-pills">
        <li>
            <a href="{{ path('anomaly_ro', {'projectId':projectId, 'type': anomalyType}) }}" class="btn btn">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back to the list
            </a>
        </li>
    </ul>
{% endblock %}

src/AIE/Bundle/AnomalyBundle/Resources/views/RepairOrderRegistrar/index.html.twig
{% extends 'AIEAnomalyBundle:Default:layout.html.twig' %}

{% block content -%}
    <h1>{{ title|default('Repair Order Register') }}</h1>

    {% include 'AIEAnomalyBundle:Registrar:search.html.twig' %}
    {% if not(project.isSetup['isSetup']) %}
    <div class="row">
        <div class="col-lg-12" style="margin-top: 20px;">
            <div class="alert alert-warning">
                <b>Access is not available.</b><br/>Setup the following lists to get access to this functionality.
                <ul>
                    {{ (project.isSetup['missing']['locations']) ? '<li>Locations</li>' }}
                    {{ (project.isSetup['missing']['classifications']) ? '<li>Classifications</li>' }}
                    {{ (project.isSetup['missing']['threats']) ? '<li>Threats</li>' }}
                    {{ (project.isSetup['missing']['actionOwners']) ? '<li>Action Owners</li>' }}
                    {{ (project.isSetup['missing']['codes']) ? '<li>Codes & Standards</li>' }}
                    {{ (project.isSetup['missing']['risk']) ? '<li>Risk Matrix or Criticality Ranking</li>' }}
                </ul>
            </div>
        </div>
    </div>
    {% else %}

        <table class="records_list">
            <thead>
            <tr>
                <th>Repair Order ID</th>
                <th>Anomaly ID (Registrar ID)</th>
                <th>Asset Tag Number</th>
                <th>Repair Order Description</th>
                <th>Technical Expiry Date</th>
                <th>
                    {% if class(project) == 'RiskProject' %}
                        {{ 'Risk' }}
                    {% else %}
                        {{ 'Criticality' }}
                    {% endif %}
                </th>
                <th>Repair Priority</th>
                <th>Status</th>
                <th>SPA</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for entity in entities | sortbyfield('expiryDate','desc') %}
                {% set anomalyType = entity.anomaly.code|lower %}
                <tr>
                    <td>
                        <a href="{{ path('anomaly_ro_show', { 'projectId': projectId, 'id': entity.id, 'type': anomalyType }) }}">{{ entity.fullId }}</a>
                        {% if status[entity.id] != 'final' %}
                            <span class="anomaly-status {{ status[entity.id] }}">
                        {{ entity.tagChoices[status[entity.id]]['label'] }}
                        </span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('anomaly_' ~ anomalyType ~ '_show', { 'projectId': projectId, 'id': entity.anomaly.id }) }}">{{ entity.anomaly.anomalyCustomId }} ({{ entity.anomaly.fullId }})</a>
                    </td>
                    <td>{{ entity.anomaly.assetTagNumber }}</td>
                    <td>{{ entity.description }}</td>
                    <td>{% if entity.expiryDate %}{{ entity.expiryDate|date }}{% endif %}</td>
                    <td>
                        {% if (entity.anomaly.probability is not null and entity.anomaly.consequence is not null ) or entity.anomaly.criticality is not null or entity.anomaly.fabricMaintenanceCriticality is not null  %}
                            {% set project_type = class(project) %}
                            {% if project_type == 'RiskProject' %}
                                {% set matrix = project.riskMatrix %}
                                {{ matrix.risk(entity.anomaly.consequence, entity.anomaly.probability) }}
                            {% else %}
                                {% if project.enableFMCriticality and entity.anomaly.isFabricMaintenanceCriticality %}
                                    <span class="custom-criticality-span" style="background-color:{{ '#' ~ project.FMCriticalityColorsArray[entity.anomaly.fabricMaintenanceCriticality] }}"><b>{{ project.FMCriticalityArray[entity.anomaly.fabricMaintenanceCriticality] }}</b></span>
                                {% else %}
                                    <span class="custom-criticality-span" style="background-color:{{ '#' ~ project.enabledCriticalityColors[entity.anomaly.criticality] }}"><b>{{ project.enabledCriticalityChoices[entity.anomaly.criticality] }}</b></span>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            {{- '-' -}}
                        {% endif %}
                    </td>
                    <td>{{ entity.repairPriority }}</td>
                    <td>{{ entity.statusChoices[entity.status] }}</td>
                    <td>{{ (entity.spa.userId)?users[entity.spa.userId]:'' }}</td>
                    <td>
                        {% include "AIEAnomalyBundle:ActionRegistrar:navigation_list.html.twig" with {'entity': entity, 'status' : status, 'granted_list': granted_list} only %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}

{% endblock %}


src/AIE/Bundle/AnomalyBundle/Resources/views/RepairOrderRegistrar/master.html.twig
{% extends 'AIEAnomalyBundle:RepairOrderRegistrar:index.html.twig' %}
{% set title = typeName ~ ' Repair Order Register' %}

src/AIE/Bundle/AnomalyBundle/Resources/views/RepairOrderRegistrar/show.html.twig
{% extends 'AIEAnomalyBundle:ActionRegistrar:show.html.twig' %}

{% set anomalyType = entity.anomaly.code|lower %}

{% block content -%}
    <h1>Repair Order Register</h1>

    {{ parent() }}

    <ul class="nav nav-pills">

        <li>
            <a href="{{ path('anomaly_ro', {'projectId': projectId, 'type' : anomalyType }) }}" class="btn btn">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back to the list
            </a>
        </li>

        <li>
            <a href="{{ path('anomaly_ro_edit', { 'projectId': projectId, 'id': entity.id, 'type': anomalyType }) }}" class="btn btn">
                <span class="glyphicon glyphicon glyphicon-edit" aria-hidden="true"></span> Edit
            </a>
        </li>

    </ul>
{% endblock %}

src/AIE/Bundle/AnomalyBundle/Resources/views/RepairOrderRegistrar/showdeferral.html.twig
{% set anomalyType = entity.anomaly.code|lower %}

{% block content %}

    {{ form_start(form) }}
    {{ form_errors(form) }}

    {% embed 'AIEAnomalyBundle:ActionRegistrar:form.html.twig' with {'show_attachments': false} %}
        {% block attachments %}{% endblock %}
    {% endembed %}

    {{ form_row(form.status) }}
    {{ form_row(form.spa) }}

    {{ form_rest(form) }}
    {% if class(project) == 'RiskProject' %}
        <input type="hidden" value="{{ project.riskMatrix.matrix }}" id="risk-matrix"/>
    {% endif %}
    {{ form_end(form) }}

    <ul class="nav nav-pills">
        <li>
            <a href="{{ path('anomaly_ro', {'projectId': projectId, 'type' : anomalyType }) }}" class="btn btn">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back to the list
            </a>
        </li>
        <li>
            <a href="{{ path('anomaly_ro_edit', { 'projectId': projectId, 'id': entity.id, 'type': anomalyType }) }}" class="btn btn">
                <span class="glyphicon glyphicon glyphicon-edit" aria-hidden="true"></span> Edit
            </a>
        </li>
    </ul>
{% endblock %}